
[workspace]
members = [
    "happenings_frontend",
    "common",
    "happenings_backend",
    "happenings_macro",
    "happenings_lib",
    "leptos_axum_hack",
]
resolver = "2"

[workspace.dependencies]
leptos_axum_hack = { { workspace = true }}
# surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }
anyhow = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true, features = ["cookie"] }
axum-macros = { workspace = true }
axum-test = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
common = { workspace = true }
derive_builder = { workspace = true }
dotenv = { workspace = true }
figment = { workspace = true, features = ["toml", "env"] }
happenings_lib = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true, features = ["server-auto", "tokio", "http1"] }
leptos = { workspace = true }
leptos_axum = { workspace = true }
mime_guess = { workspace = true }
oauth2 = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true, default-features = false, features = [
    "rustls-tls",
    "cookies",
    "trust-dns",
    "json",
] }
rust-embed = { workspace = true }
scopeguard = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sha256 = { workspace = true }
surrealdb = { workspace = true }
tokio = { workspace = true, features = ["full", "macros", "rt-multi-thread"] }
tokio-util = "0.7.10"
tower = "0.4.13"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
wasm-bindgen-cli-support = "0.2.89"

# # TODO - just for wasm?
# [profile.release]
# #  inherits = "release"
# opt-level = 'z'
# lto = true
# codegen-units = 1
