
[workspace]
members = ["frontend", "common", "happenings"]
resolver = "2"

[[bin]]
name = "happenings"
path = "src/main.rs"

[package]
name = "happenings-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
happenings = { path = "happenings" }
anyhow = "1.0.75"
oauth2 = "4.4.2"
chrono = { version = "0.4.31", features = ["serde"] }
surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }
axum = "0.7.2"
serde = { version = "1.0.193", features = ["derive"] }
common = { path = "common" }
reqwest = { version = "0.11.22", default-features = false, features = [
    "rustls-tls",
    "cookies",
    "trust-dns",
    "json",
] }
rand = "0.8.5"
sha256 = "1.4.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
dotenv = "0.15.0"
rust-embed = "8.1.0"
figment = { version = "0.10.12", features = ["toml", "env"] }
tokio = { version = "1.34.0", features = ["full", "macros", "rt-multi-thread"] }
hyper = "1.0.1"
tower = "0.4.13"
mime_guess = "2.0.4"
leptos = "0.5.4"
tokio-util = "0.7.10"
axum-macros = "0.4.0"
hyper-util = { version = "0.1.1", features = ["server-auto", "tokio", "http1"] }
once_cell = "1.19.0"

# serde_json = "1.0.108"
# tower-http = { version = "0.5.0", features = ["tracing", "trace"] }
# futures-util = "0.3.29"
# serde_qs = "0.12.0"
# leptos_axum = "0.5.4"
# futures = "0.3.30"

[build-dependencies]
anyhow = "1.0.75"
jobserver = "0.1.27"
wasm-bindgen-cli-support = "0.2.89"
frontend = { path = "./frontend", optional = true }
#  frontend = { path = "./frontend", artifact = "cdylib", target = "wasm32-unknown-unknown" }

[dev-dependencies]
axum-test = "14.0.0"
# frontend = { path = "frontend", artifact = "cdylib", target = "wasm32-unknown-unknown" }
# frontend = { path = "frontend" }
