
[workspace]
members = ["frontend", "common"]

[package]
name = "happenings"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

tokio = { version = "1.34.0", features = ["full", "macros", "rt-multi-thread"] }
dotenv = "0.15.0"
tracing = "0.1.40"
axum = "0.7.2"
hyper = "1.0.1"
tower = "0.4.13"
hyper-util = { version = "0.1.1", features = ["server-auto", "tokio", "http1"] }
oauth2 = "4.4.2"
rust-embed = "8.1.0"
mime_guess = "2.0.4"
surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }
serde = { version = "1.0.193", features = ["derive"] }
anyhow = "1.0.75"
reqwest = { version = "0.11.22", features = ["json"] }
serde_json = "1.0.108"
chrono = { version = "0.4.31", features = ["serde"] }
common = { path = "common" }
figment = { version = "0.10.12", features = ["toml", "env"] }
tower-http = { version = "0.5.0", features = ["tracing", "trace"] }
futures-util = "0.3.29"

[build-dependencies]
anyhow = "1.0.75"
wasm-bindgen-cli-support = "0.2.89"
# frontend = { path = "frontend", artifact = "cdylib", target = "wasm32-unknown-unknown" }
# frontend = { path = "frontend" }
