[package]
 name = "common"
 version = "0.1.0"
 edition = "2021"

 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
 serde = { version = "1.0.193", features = ["derive"] }
 reqwest = { version = "0.11.22", default-features = false, features = [
  "rustls-tls",
  "cookies",
  "trust-dns",
  "json",
 ] }
 url = { version = "2.5.0", features = ["serde"] }
